version: '3.9'

services:
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./src/main/kotlin/com/techandteach/framework/database/schema.sql:/schema.sql
      - ./src/main/kotlin/com/techandteach/framework/database/test-schema.sql:/test-schema.sql
    ports:
      - "5432:5432"
    networks:
      - travelagency

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mail@domain.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 9000:80
    depends_on:
      - pg
    networks:
      - travelagency

networks:
  travelagency:
    name: travelagency
    driver: bridge
